# Default Drupal services with CORS enabled for local development.
parameters:
  session.storage.options:
    gc_probability: 1
    gc_divisor: 100
    gc_maxlifetime: 200000
    cookie_lifetime: 2000000
  twig.config:
    debug: false
    auto_reload: null
    cache: true
  renderer.config:
    required_cache_contexts: ['languages:language_interface', 'theme', 'user.permissions']
    auto_placeholder_conditions:
      max-age: 0
      contexts: ['session', 'user']
      tags: []
  http.response.debug_cacheability_headers: false
  cors.config:
    enabled: true
    allowedHeaders: ['x-csrf-token', 'authorization', 'content-type', 'content-disposition', 'accept', 'origin', 'x-requested-with']
    allowedMethods: ['*']
    allowedOrigins: ['http://localhost:3000']
    exposedHeaders: false
    maxAge: false
    supportsCredentials: true

services:
  cache.backend.memory:
    class: Drupal\Core\Cache\MemoryBackendFactory
